version: "3"
services:
  next-wira:
    image:  next-wira_app:latest
    container_name: next-wira
    volumes:
      - .:/app
    command: npm run dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
