name: CI
on: [push, pull_request]
jobs:
  # test:
  #   ...
  deploy:
    name: "Deploy to docker"
    runs-on: ubuntu-latest
    environment : Docker-Staging
    env:
      SSH_KEY: ${{ secrets.DOCKER_SSH_KEY }}
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    # needs: test
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/docker.key
          chmod 600 ~/.ssh/docker.key
          cat >>~/.ssh/config <<END
          Host docker
            HostName 45.119.160.27
            User atom
            IdentityFile ~/.ssh/docker.key
            StrictHostKeyChecking no
          END
        env:
          SSH_KEY: ${{ secrets.DOCKER_SSH_KEY }}
      - name: Pull changes from the server
        run: ssh atom@45.119.160.27 "cd /app/next-project/next-wira && sudo git pull origin main"
      
